### ISSUE TITLE
ucf-web-migrate 工具需求

### ISSUE THREAD

**Issue by GuoYongfeng** [iuap-design/ucf-web#2]
## ucf-web-migrate 

一个 CLI 工具，旨在帮助uba开发者用户快速将其工程迁移升级为 ucf-web 微前端框架。

## 使用方式

```
# 全局安装
$ npm i ucf-web-migrate  -g

# 进入到原基于uba的工程跟目录下执行 migrate 
$ cd xx && migrate init
```

### 一、修改原工程的目录结构和文件，替换为遵循ucf-web框架规范的目录名称和文件名称；
1、删除`mock`目录、`.babelrc`文件、`postcss.config.js`文件、`uba.mock.js`文件、`node_modules`目录。
2、新增目录 `ucf-common`，并执行 `mv src ucf-common`
3、新增`ucf-apps`目录，执行 `mv ucf-common/src/pages/* ucf-apps`
4、读取uba.config.js文件内容并将其删除，同时新增默认的ucf.config.js文件

### 二、修改配置文件
1、读取并修改 `package.json`
1.1 读取`dependencies`配置
1.2 修改`scripts`字段，新增`ucf-scripts`的依赖。

2、读取`uba.config.js`中的配置，替换修改为ucf.config.js的配置，主要修改点：
2.1 context 读取和修改
2.2 proxy 读取和修改
2.3 global 环境变量读取和修改
2.4 alias 别名读取和修改（**这个影响点较大，修改后需要去自动化替换业务文件中的代码**）

### 三、修改业务代码原文件（公共资源的依赖路径）

```
# 如原配置的别名为：
utils: path.resolve(__dirname, 'src/utils/'),

....

# 对应的代码
import { Generate } from 'utils';
```

**Comment by wxgg** [comment]
【主线任务领取成功】

**Comment by kvkens** [comment]
已开发
